var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/clock-test/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0x.bl7i._.js")
R.c("server/chunks/ssr/node_modules_next_dist_06u0kr8._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_0v7ibg0.js")
R.c("server/chunks/ssr/[root-of-the-server]__0kv1ijr._.js")
R.c("server/chunks/ssr/[root-of-the-server]__09z7o2x._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0239o7g._.js")
R.c("server/chunks/ssr/src_app_error_tsx_0oqfei_._.js")
R.c("server/chunks/ssr/_00zu~09._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0ee1czk._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0lgvd_..js")
R.c("server/chunks/ssr/_next-internal_server_app_clock-test_page_actions_0b6c2n8.js")
R.m(17700)
module.exports=R.m(17700).exports
